// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANCZYdkEH-8PKVt3IpBA10vNqeibqxOEw',
    appId: '1:473181664730:web:470a50a74f81e1b6e33ce3',
    messagingSenderId: '473181664730',
    projectId: 'parking-app-ffe32',
    authDomain: 'parking-app-ffe32.firebaseapp.com',
    storageBucket: 'parking-app-ffe32.firebasestorage.app',
    measurementId: 'G-2CFV7TQS1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZuuMqJtvqp13RjvBxsrlF3DUXGP3xpO4',
    appId: '1:473181664730:android:12ea3853b56e3c59e33ce3',
    messagingSenderId: '473181664730',
    projectId: 'parking-app-ffe32',
    storageBucket: 'parking-app-ffe32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmhZ1TFyrGK_tKkuo-4gvp-vVT2xhhHA',
    appId: '1:473181664730:ios:b761f5f23adaaea1e33ce3',
    messagingSenderId: '473181664730',
    projectId: 'parking-app-ffe32',
    storageBucket: 'parking-app-ffe32.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );
}
